apiVersion: v1
kind: ConfigMap
metadata:
  name: movisabio-config
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@movisabio-db-svc:5432/movisabio"
  KAFKA_BROKERS: "movisabio-kafka-svc:9092"
