from typing import Dict, Tuple
from datetime import datetime
from src.services.demand.models.schemas import ActivityZone

class DemandForecaster:
    """
    Generates trip volume forecasts based on territorial activity.
    """
    
    def forecast_zone_generation(self, zone: ActivityZone, target_hour: int) -> Tuple[int, float]:
        """
        Estimates trips generated by a zone at a specific hour, returning (volume, confidence).
        """
        # Base generation based on population and employment
        base_trips = (zone.population_estimate * 1.5) + (zone.employment_estimate * 2.0)
        
        # Temporal modifier
        intensity = zone.activity_intensity_profile.get(str(target_hour), 0.5)
        
        volume = int(base_trips * intensity / 24) # Simplified hourly distribution
        
        # Confidence calculation
        confidence = 0.85
        if intensity < 0.2 or intensity > 1.8:
            confidence = 0.70 # Lower confidence during extreme peaks or dead hours
            
        return volume, confidence
