apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: pilot01-
commonLabels:
  env: pilot
  intersection: ID_01

patchesStrategicMerge:
  - configmap-patch.yaml
